#!/usr/bin/env bash
# Deploy and manage an official Docker Registry pull-through cache.
set -Eeuo pipefail
IFS=$'\n\t'

readonly STATE_DIR="${DOCKERHUB_MIRROR_STATE_DIR:-/var/lib/dockerhub-mirror}"
readonly COMPOSE_FILE="$STATE_DIR/compose.yaml"
readonly ENV_FILE="$STATE_DIR/.env"
readonly DAEMON_JSON='/etc/docker/daemon.json'
readonly IMAGE='registry:2'
readonly DEFAULT_REMOTE='https://registry-1.docker.io'
readonly DEFAULT_PORT_START=10305
readonly DEFAULT_PORT_END=10307

MODE='menu'
PORT=''
LISTEN_ADDR='0.0.0.0'
REMOTE_URL="$DEFAULT_REMOTE"
MIRROR_URL=''
INSECURE=0
ASSUME_YES=0
TEST_IMAGE='alpine:3.21'
IMAGE_REPOSITORY=''
IMAGE_REFERENCE=''

die() { printf '错误：%s\n' "$*" >&2; exit 1; }
note() { printf '\n== %s ==\n' "$*"; }
need() { command -v "$1" >/dev/null 2>&1 || die "缺少命令：$1"; }
confirm() {
  local answer
  [[ $ASSUME_YES -eq 1 ]] && return 0
  read -r -p "$1 [y/N]: " answer
  [[ "$answer" == y || "$answer" == Y || "$answer" == yes || "$answer" == YES ]]
}
usage() {
  cat <<'EOF'
用法：sudo bash dockerhub-mirror.sh [选项]

默认进入菜单。服务端（国外 VPS）示例：
  sudo bash dockerhub-mirror.sh --server --port 10305 --public-url http://198.51.100.10:10305
客户端（国内 Docker 主机）示例：
  sudo bash dockerhub-mirror.sh --client --mirror https://mirror.example.com

选项：
  --server                 部署/更新 Docker Hub pull-through cache
  --client                 配置本机 Docker 使用镜像缓存
  --status                 查看服务端容器或本机镜像配置
  --uninstall              删除服务端 Compose 项目（数据默认保留）
  --port PORT              服务端监听 TCP 端口；默认自动选择 10305-10307
  --listen ADDRESS         服务端绑定地址（默认 0.0.0.0）
  --public-url URL         客户端应访问的完整 URL（服务端必填）
  --mirror URL             客户端镜像 URL（必填）
  --insecure               允许 HTTP 镜像；客户端会写 insecure-registries
  --image IMAGE            部署后拉取验证的 Docker Hub 镜像（默认 alpine:3.21）
  --yes                    跳过确认（仅自动化使用）
EOF
}

port_free() {
  local p="$1"
  ! ss -H -ltn "sport = :$p" 2>/dev/null | grep -q . &&
    ! ss -H -lun "sport = :$p" 2>/dev/null | grep -q .
}
choose_port() {
  need ss
  if [[ -n "$PORT" ]]; then
    [[ "$PORT" =~ ^[0-9]+$ && $PORT -ge 1 && $PORT -le 65535 ]] || die "无效端口：$PORT"
    port_free "$PORT" || die "TCP 或 UDP 已占用端口：$PORT"
    return
  fi
  local p
  for ((p=DEFAULT_PORT_START; p<=DEFAULT_PORT_END; p++)); do
    if port_free "$p"; then PORT="$p"; return; fi
  done
  die "10305-10307 没有空闲 TCP/UDP 端口，请用 --port 指定。"
}

parse_image() {
  local value="$1" name
  [[ "$value" != */* || "${value%%/*}" != *.* && "${value%%/*}" != *:* && "${value%%/*}" != localhost ]] ||
    die "验证镜像只能来自 Docker Hub：$1"
  if [[ "$value" == *@* ]]; then
    name="${value%@*}"
    IMAGE_REFERENCE="${value#*@}"
  else
    name="$value"
    IMAGE_REFERENCE='latest'
    if [[ "$name" == *:* && "${name##*:}" != */* ]]; then
      IMAGE_REFERENCE="${name##*:}"
      name="${name%:*}"
    fi
  fi
  [[ -n "$name" && -n "$IMAGE_REFERENCE" ]] || die "无效验证镜像：$1"
  [[ "$name" == */* ]] && IMAGE_REPOSITORY="$name" || IMAGE_REPOSITORY="library/$name"
}

write_server_files() {
  local public_url="$1"
  mkdir -p "$STATE_DIR/data"
  chmod 700 "$STATE_DIR" "$STATE_DIR/data"
  cat >"$COMPOSE_FILE" <<EOF
services:
  dockerhub-mirror:
    image: $IMAGE
    container_name: dockerhub-mirror
    restart: unless-stopped
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_PROXY_REMOTEURL: $REMOTE_URL
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_STORAGE_DELETE_ENABLED: "false"
    volumes:
      - $STATE_DIR/data:/var/lib/registry
    ports:
      - "$LISTEN_ADDR:$PORT:5000"
EOF
  cat >"$ENV_FILE" <<EOF
# Generated by dockerhub-mirror.sh. Keep this directory private.
MIRROR_PUBLIC_URL=$public_url
MIRROR_PORT=$PORT
MIRROR_IMAGE=$IMAGE
EOF
  chmod 600 "$ENV_FILE"
  chmod 644 "$COMPOSE_FILE"
}

server_status() {
  need docker
  if [[ -f "$COMPOSE_FILE" ]]; then
    (cd "$STATE_DIR" && docker compose -f "$COMPOSE_FILE" ps) || true
    printf '\n缓存目录：%s\n' "$STATE_DIR/data"
  else
    printf '未发现服务端配置：%s\n' "$COMPOSE_FILE"
    if [[ -f "$DAEMON_JSON" ]]; then
      python3 - "$DAEMON_JSON" <<'PY'
import json, sys
try:
    data = json.load(open(sys.argv[1], encoding='utf-8'))
    print('本机 registry-mirrors：', data.get('registry-mirrors', []))
    print('本机 insecure-registries：', data.get('insecure-registries', []))
except Exception as e:
    print(f'无法读取 daemon.json：{e}')
PY
    fi
  fi
}

server_install() {
  need docker; need ss; need curl
  choose_port; parse_image "$TEST_IMAGE"
  local public_url="${MIRROR_URL:-}"
  [[ -n "$public_url" ]] || {
    local host
    host=$(hostname -I 2>/dev/null | awk '{print $1}')
    [[ -n "$host" ]] || host='<OVH公网IP或域名>'
    public_url="http://$host:$PORT"
    [[ $INSECURE -eq 1 ]] || printf '提示：当前未提供 HTTPS 域名，自动示例为 HTTP；正式接入建议使用域名和 TLS。\n'
  }
  [[ "$public_url" =~ ^https?://[^[:space:]/]+(:[0-9]+)?/?$ ]] || die "--public-url 必须是完整 URL"
  public_url="${public_url%/}"
  if [[ "$public_url" == http://* && $INSECURE -eq 0 ]]; then
    printf '警告：HTTP mirror 需要在国内客户端使用 --insecure，流量未加密。\n'
  fi
  note "服务端部署参数"
  printf '监听：%s:%s（TCP/UDP 均检查）\n远端：%s\n公开 URL：%s\n数据：%s/data\n' "$LISTEN_ADDR" "$PORT" "$REMOTE_URL" "$public_url" "$STATE_DIR"
  confirm '写入 Compose 并启动 Docker Hub 缓存？' || { printf '未做修改。\n'; return 0; }
  write_server_files "$public_url"
  (cd "$STATE_DIR" && docker compose -f "$COMPOSE_FILE" pull && docker compose -f "$COMPOSE_FILE" up -d)
  sleep 2
  docker inspect dockerhub-mirror --format '容器状态：{{.State.Status}}' 2>/dev/null || true
  if curl -fsS --max-time 10 "$public_url/v2/" >/dev/null; then
    printf 'Registry API：可访问\n'
  else
    printf 'Registry API：暂未通过，请检查防火墙、端口和 URL。\n' >&2
  fi
  if curl -fsS --max-time 90 \
    -H 'Accept: application/vnd.docker.distribution.manifest.v2+json, application/vnd.oci.image.manifest.v1+json' \
    "$public_url/v2/$IMAGE_REPOSITORY/manifests/$IMAGE_REFERENCE" >/dev/null; then
    printf 'Docker Hub 缓存验证：%s manifest 已经由 Registry 代理获取\n' "$TEST_IMAGE"
  else
    printf 'Docker Hub 缓存验证未通过；容器仍已启动，请检查 Registry 日志和 Docker Hub 连通性。\n' >&2
  fi
  printf '\n国内客户端配置示例：\n  sudo bash dockerhub-mirror.sh --client --mirror %s%s\n' "$public_url" "$([[ "$public_url" == http://* ]] && printf ' --insecure' || true)"
}

client_config() {
  need docker; need python3
  [[ -n "$MIRROR_URL" ]] || die '--mirror 需要完整的镜像 URL，例如 https://mirror.example.com:10305'
  MIRROR_URL="${MIRROR_URL%/}"
  [[ "$MIRROR_URL" =~ ^https?://[^[:space:]/]+(:[0-9]+)?$ ]] || die "无效 mirror URL：$MIRROR_URL"
  [[ "$MIRROR_URL" == https://* || $INSECURE -eq 1 ]] || die 'HTTP mirror 必须显式加 --insecure。'
  note "将配置本机 Docker"
  printf '镜像：%s\n配置文件：%s\n' "$MIRROR_URL" "$DAEMON_JSON"
  confirm '写入 daemon.json 并重启 Docker？' || { printf '已恢复，不修改 Docker。\n'; return 0; }
  local backup
  if [[ -f "$DAEMON_JSON" ]]; then
    backup="$DAEMON_JSON.bak.dockerhub-mirror.$(date +%Y%m%d%H%M%S)"
    cp -a "$DAEMON_JSON" "$backup"
  else
    backup='（原文件不存在）'
  fi
  python3 - "$DAEMON_JSON" "$MIRROR_URL" "$INSECURE" <<'PY'
import json, os, sys
path, mirror, insecure = sys.argv[1], sys.argv[2], sys.argv[3] == '1'
try:
    with open(path, encoding='utf-8') as f: data=json.load(f)
except FileNotFoundError: data={}
except json.JSONDecodeError as e: raise SystemExit(f'daemon.json JSON 无效：{e}')
data['registry-mirrors']=[mirror]
if insecure:
    values=data.get('insecure-registries', [])
    host=mirror.split('://',1)[1]
    if host not in values: values.append(host)
    data['insecure-registries']=values
tmp=path+'.dockerhub-mirror.tmp'
with open(tmp,'w',encoding='utf-8') as f:
    json.dump(data,f,ensure_ascii=False,indent=2); f.write('\n')
os.chmod(tmp,0o644); os.replace(tmp,path)
PY
  if systemctl restart docker 2>/dev/null; then
    docker info --format 'Docker mirrors：{{json .RegistryConfig.Mirrors}}' 2>/dev/null || true
  else
    printf 'Docker 重启失败，保留备份：%s\n' "$backup" >&2; return 1
  fi
  printf '客户端配置完成。只对未显式指定其他 registry 的 Docker Hub 镜像生效。\n'
}

uninstall_server() {
  need docker
  [[ -f "$COMPOSE_FILE" ]] || { printf '未发现服务端 Compose。\n'; return 0; }
  printf '将停止并删除 dockerhub-mirror 容器，缓存数据保留在 %s/data。\n' "$STATE_DIR"
  confirm '继续？' || return 0
  (cd "$STATE_DIR" && docker compose -f "$COMPOSE_FILE" down)
  printf '容器已删除，缓存数据未删除。\n'
}

menu() {
  while :; do
    printf '\nDocker Hub Mirror（Registry pull-through cache）\n1. 部署/更新服务端缓存\n2. 配置本机 Docker 客户端\n3. 查看状态\n4. 卸载服务端容器（保留缓存）\n0. 返回\n'
    local choice
    read -r -p '请选择：' choice || return
    case "$choice" in
      1) server_install ;;
      2) client_config ;;
      3) server_status ;;
      4) uninstall_server ;;
      0) return ;;
      *) printf '无效选择。\n' ;;
    esac
  done
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --server) MODE='server' ;;
    --client) MODE='client' ;;
    --status) MODE='status' ;;
    --uninstall) MODE='uninstall' ;;
    --port) [[ $# -ge 2 ]] || die '--port 缺少值'; PORT="$2"; shift ;;
    --listen) [[ $# -ge 2 ]] || die '--listen 缺少值'; LISTEN_ADDR="$2"; shift ;;
    --public-url|--mirror) [[ $# -ge 2 ]] || die "$1 缺少值"; MIRROR_URL="$2"; shift ;;
    --insecure) INSECURE=1 ;;
    --image) [[ $# -ge 2 ]] || die '--image 缺少值'; TEST_IMAGE="$2"; shift ;;
    --yes) ASSUME_YES=1 ;;
    --help|-h) usage; exit 0 ;;
    *) die "未知选项：$1" ;;
  esac
  shift
done

case "$MODE" in
  menu) menu ;;
  server) server_install ;;
  client) client_config ;;
  status) server_status ;;
  uninstall) uninstall_server ;;
esac
